
name: Stock Daddy Scanner

on:
  schedule:
    - cron: '*/10 13-20 * * 1-5'   # every 10 minutes during cash session UTC window
    - cron: '0 12 * * 1-5'         # 12:00 UTC ~ 08:00 ET reset
  workflow_dispatch: {}

jobs:
  reset:
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 12 * * 1-5' }}
    runs-on: ubuntu-latest
    steps:
      - name: Nightly reset
        run: |
          curl -X POST -sS https://YOUR-VERCEL-APP.vercel.app/api/reset || true

  scan:
    if: ${{ github.event_name == 'schedule' && github.event.schedule != '0 12 * * 1-5' }}
    runs-on: ubuntu-latest
    steps:
      - name: Ping scan endpoint
        run: |
          curl -sS https://YOUR-VERCEL-APP.vercel.app/api/scan || true
